#This is a multi-stage docker-file 
FROM alpine:latest AS builder
RUN apk add --no-cache gcc musl-dev
COPY hello.c .
RUN gcc -o hello hello.c
#This was the first part
FROM alpine:latest
COPY --from=builder /hello /hello
CMD ["./hello"]

#To run this container use the command
#docker build -f Dockerfile-multistage -t multi-stage .